version: '3.5'

services:
  web:
    build: .
    command: python weather_project/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/meta_weather
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres
    container_name: weather_db
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: admin
      POSTGRES_DB: db01
      POSTGRES_INITDB_ARGS: "-A md5"